### ISSUE TITLE
Question: asking ImagineVision for Linux firmware source

### ISSUE THREAD

**Issue by oldmud0** [storyboardcreativity/Z-Camera-E1-Reverse-Engineering#1]
I am delighted by your progress on reverse engineering the Z CAM E1! We actually use this on a small UAV to take pictures, but we have found the firmware to be extremely janky and haven't found any time to do any reverse engineering work ourselves.

But you have discovered that the UI side uses Linux and Qt - which immediately implies that since Linux is GPLv2, aren't we legally entitled to receive their branch of the Linux source tree? I don't remember how far the legal requirement goes, but I know that Netgear had to go so far as to releasing their entire firmware kit to allow developers to build their own firmware for all of Netgear's Linux-based routers. Who knows what other open-source software they may be using as well that was included without a license.

It will not give us all the answers, but it may aid in further reverse engineering work.

**Comment by storyboardcreativity** [comment]
@oldmud0, I've just sent a request to Z-Cam about Linux sources. Let's wait for some time. Thank you!

Anyway, you can check my E1 firmware repacker. Code is very draft, but works.

**Comment by storyboardcreativity** [comment]
Tried many times. They don't answer me and ban me everywhere.
